export const FETCH_CATEGORIES = 'category/FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'category/FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'category/FETCH_CATEGORIES_FAILURE';
